#!/usr/bin/nft -f

flush ruleset

table inet filter {
  chain input {
    type filter hook input priority filter;

    iif lo accept

    icmp type != {
      timestamp-request,
      timestamp-reply,
      info-request,
      info-reply,
      address-mask-request,
      address-mask-reply
    } accept
    ip6 nexthdr icmpv6 accept

    ct state invalid drop
    ct state { established, related } accept

    counter drop
  }

  chain forward {
    type filter hook forward priority filter;
    drop
  }

  chain output {
    type filter hook output priority filter;
  }
}
